site_name: Qitmeer/ Meerlabs Community Documents

repo_name: Qitmeer/community_docs
repo_url: https://github.com/Qitmeer/community_docs

nav:
  - Home: index.md
  - About BlockDAG: What_is_BlockDAG.md
  - Running Qitmeer Node: Installation_Running_qng_node.md
  - QNG - EVM & Deploying Smart Contracts: meerEVM_deploying_SmartContracts.md
  - Solidity Tutorial (Part 1): solidity_tutorial_basics_part_1.md
  - Solidity Tutorial (Part 2): solidity_tutorial_basics_part_2.md
  - Solidity Tutorial (Part 3): solidity_tutorial_basics_part_3.md
  - Amana Deployment Tutorial (using Amana Privnet Launcher): amana_tutorial.md
  

theme:
  name: material
  icon: 
    repo: fontawesome/brands/github
  features:
    - navigation.footer
  palette:
    primary: green
  

extra: 
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/+L5nExcssmOxjZTc0



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

